env:
  # For publishing and using the docker image
  QUAY_REPO: quay.io/tylerauerbeck


steps:
  - label: "Docker builds"
    plugins:
      - chronotc/monorepo-diff#v2.3.0:
          watch:
            - path:
                - "Dockerfile"
              config:
                command: "echo core" 
                label: ":whale: Build Core"
                retry:
                  automatic:
                  - limit: 2
                    exit_status: -1
            - path:
                - "Dockerfile.util"
              config:
                command: "echo util" 
                label: ":whale: Build Util"
                retry:
                  automatic:
                  - limit: 2
                    exit_status: -1
          wait: true
