env:
  # For publishing and using the docker image
  QUAY_REPO: quay.io/tylerauerbeck

steps:
  - label: ":partyparrot: Creating the pipeline"
    plugins:
      - Zegocover/git-diff-conditional#v1.1.1:
          dynamic_pipeline: ".buildkite/dyn-1.yaml"
          steps:
            - label: "core"
              env:
                thing: "core"
              include:
                - "Dockerfile"
            - label: "util"
              env:
                thing: "util"
              include:
                - "Dockerfile.util"
